from django.core.management.base import BaseCommand
import pandas as pd
from fhtways.models import Node, Edge

class Command(BaseCommand):
    help = 'Loads data from CSV files into the database.'

    def handle(self, *args, **options):
        # Path to CSV data
        base_path = '/autogenerated-directions-FHTW/backend/fhtways/data_csv/'

        # loads Nodes und Edges from CSV-files
        node_files = ['A2_nodes.csv', 'F2_nodes.csv', 'F3_nodes.csv', 'F4_nodes.csv']
        edge_files = ['A2_edges.csv', 'F2_edges.csv', 'F3_edges.csv', 'F4_edges.csv']

        # imoport Nodes
        for file_name in node_files:
            file_path = base_path + file_name
            self.stdout.write(f"Importing nodes from {file_path}")
            df_nodes = pd.read_csv(file_path)
            for index, row in df_nodes.iterrows():
                Node.objects.update_or_create(
                    node_id=row['node_id'],
                    defaults={
                        'coord': (row['coord_x'], row['coord_y']),
                        'type': row['type']
                    }
                )

        # import Edges
        for file_name in edge_files:
            file_path = base_path + file_name
            self.stdout.write(f"Importing edges from {file_path}")
            df_edges = pd.read_csv(file_path)
            for index, row in df_edges.iterrows():
                start_node = Node.objects.get(node_id=row['start_node'])
                end_node = Node.objects.get(node_id=row['end_node'])
                Edge.objects.update_or_create(
                    start_node=start_node,
                    end_node=end_node,
                    defaults={
                        'weight': row['weight'],
                        'description': row['description']
                    }
                )

        self.stdout.write(self.style.SUCCESS('Successfully imported all nodes and edges into the database.'))
